title: "Credit Card Weekly Status Dashboard"
logo: "/assets/images/Mohcine[377].png"  # Chemin relatif au projet GitHub
show_downloads: true
remote_theme: "pages-themes/slate@v0.2.0"
plugins:
  - jekyll-remote-theme
